### ISSUE TITLE
Config in fsharplint.json not being loaded

### ISSUE THREAD

**Issue by jgardella** [deviousasti/fsharp-linting-for-vs#2]
When I run the extension with a project open which has the configuration in the default file (`fsharplint.json` in the root of the repo), the configuration isn't loaded by the extension when linting. I believe this is because the extension calls into FSharpLint through `Lint.ParsedFileInformation`, and FSharpLint is looking for the default configuration in `./fsharplint.json`, from the current working directory. So the current working directory is likely the directory of the file being linted, and not necessarily the root of the repo or project.

This is probably a bigger question than just the extension. Ideally, every integration for FSharpLint should use similar rules for loading the default config, so possibly there should be a change in FSharpLint itself to make this work more consistently. But I'm not sure what would make the most sense. One option would be to load `fsharplint.json` in the current directory, or in any of the parent directories of the current directory.

**Comment by deviousasti** [comment]
That's similar to what `editorconfig` does.
It cascades rules all the way to the root.
Is there a plan for adopting it?

I'd also like to add a "Suppress > In file".

**Comment by deviousasti** [comment]
For now, I could load the file from the project file's location.
Would that be sufficient?

**Comment by aparent-emgs** [comment]
It'd be fine to be able to set the configuration from the root of a project, but it would be even more convenient if we could set it at a solution level so all projects in a solution use the same linting configuration.

**Comment by deviousasti** [comment]
If I have checked out a project as a sub-module, do we use the configuration in the project's folder or use the solution's?
Irrespective, loading from the solution root seems like a good compromise.

Are we agreed on this?

**Comment by aparent-emgs** [comment]
It'd be good for my use, don't know about others. As @jgardella said, the ideal solution would be to look in the current directory, then cascade into parent directories until we find one (and probably stop looking at the solution root, if that's possible), and as such in your example the project loaded as a submodule would still be using it's own configuration while the projects in the solution can use the solution's configuration.

But yes, if that comes at a later time it's fine, for me.

**Comment by jgardella** [comment]
@deviousasti I agree, loading from the solution root seems like the most common use case to me. I was not sure if you would always have this information though, for example if someone opened one of the projects instead of the full solution.

**Comment by deviousasti** [comment]
Released 0.2. See: https://github.com/deviousasti/fsharp-linting-for-vs#configuration

**Comment by deviousasti** [comment]
If we need to look in more places, please re-open this issue.
