### ISSUE TITLE
Move to fsprojects/fsharp-linting-for-vs?

### ISSUE THREAD

**Issue by sergey-tihon** [deviousasti/fsharp-linting-for-vs#9]
Hi @deviousasti!

Don already proposed to move fsharp-formatting-for-vs to fsprojects. https://github.com/deviousasti/fsharp-formatting-for-vs/issues/22
I think that this project also deserves more attention. Do you interested in the move?

**Comment by deviousasti** [comment]
Yes, it's definitely good to have a succession plan. 
Is there a documented process for going about this?

**Comment by sergey-tihon** [comment]
Process is described here https://github.com/fsprojects/fsprojects-admin#onboarding-process
You already invited to organisation. When you accept the invitation you will be able to transfer repository to fsprojects.
After the transfer I will update repo permission to restore you Admin access to it.

**Comment by deviousasti** [comment]
Successfully transferred both. 
Doubly scary because there are valid accounts for all manner of typos for `fsprojects`.

**Comment by sergey-tihon** [comment]
I've restored your `Admin` access to both repos. 
Thank you and welcome to fsprojects!
